apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-12-26T10:16:34Z
  name: service-cb79856b-95c5-41c8-9881-2e8b6b25aa1f
  namespace: default
  resourceVersion: "5300780"
  selfLink: /api/v1/namespaces/default/services/service-cb79856b-95c5-41c8-9881-2e8b6b25aa1f
  uid: 5275aab1-08f7-11e9-978e-54b2030b7752
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: api
    nodePort: 31852
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    deployment: cdu01-cb79856b-95c5-41c8-9881-2e8b6b25aa1f
  sessionAffinity: None
  type: LoadBalancer

