apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-12-26T10:16:23Z
  name: service-96526bd3-430d-4cb4-9f63-19c46e296c0a
  namespace: default
  resourceVersion: "7083983"
  selfLink: /api/v1/namespaces/default/services/service-96526bd3-430d-4cb4-9f63-19c46e296c0a
  uid: 4c2344e5-08f7-11e9-978e-54b2030b7752
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: rtmp
    nodePort: 30783
    port: 1935
    protocol: TCP
    targetPort: 1935
  - name: api
    nodePort: 31500
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: stats
    nodePort: 32438
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: cdu01-96526bd3-430d-4cb4-9f63-19c46e296c0a
  sessionAffinity: None
  type: LoadBalancer

