apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-12-26T10:16:26Z
  generation: 1
  labels:
    deployment: cdu01-84c3c79f-80c3-45ba-a179-43d8dbe520ea
  name: 84c3c79f-80c3-45ba-a179-43d8dbe520ea
  namespace: default
  resourceVersion: "7101821"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/84c3c79f-80c3-45ba-a179-43d8dbe520ea
  uid: 4d6da091-08f7-11e9-978e-54b2030b7752
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: cdu01-84c3c79f-80c3-45ba-a179-43d8dbe520ea
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: cdu01-84c3c79f-80c3-45ba-a179-43d8dbe520ea
    spec:
      containers:
      - image: ignaciodomin/media-streaming-engine:demo1
        imagePullPolicy: IfNotPresent
        name: cdu01-84c3c79f-80c3-45ba-a179-43d8dbe520ea
        ports:
        - containerPort: 1935
          name: int-rtmp
          protocol: TCP
        - containerPort: 80
          name: int-hls
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
