---
descriptor_schema: "https://raw.githubusercontent.com/sonata-nfv/tng-schema/master/function-descriptor/vnfd-schema.yml"

vendor: "eu.5gtango"
name: "media-aggregator-vnf"
version: "0.1"
author: "Ignacio Dominguez"
description: "Media-aggregator VNF descriptor."

cloudnative_deployment_units:
  - id: "cndu01"
    image: ignaciodomin/media-aggregator:dev
    connection_points:
      - id: "int-rtmp"
        port: 1935
      - id: "int-api"
        port: 5000
      - id: "int-stats"
        port: 8080
    parameters:                 # (optional)
        k8s_deployment:
          key1: value2
        k8s_service:
          keyA: valueB
      
# VNF connection points to the outside world
connection_points:
  - id: "rtmp"
    interface: "ipv4"
    type: "serviceendpoint"
    port: 1935
  - id: "api"
    interface: "ipv4"
    type: "serviceendpoint"
    port: 5000
  - id: "stats"
    interface: "ipv4"
    type: "serviceendpoint"
    port: 8080
  

# CNFs only use E-Tree links to map external ports to internal ports
virtual_links:
  - id: "rtmp-link"
    connectivity_type: "E-Tree"
    connection_points_reference:
      - "rtmp"
      - "cdu01:int-rtmp"
  - id: "api-link"
    connectivity_type: "E-Tree"
    connection_points_reference:
      - "api"
      - "cdu01:int-api"
  - id: "stats-link"
    connectivity_type: "E-Tree"
    connection_points_reference:
      - "stats"
      - "cdu01:int-stats"