descriptor_extension: yml
version: '0.5'
package:
  vendor: eu.5gtango
  name: ns-mediapilot-service-monitoring
  version: '0.3'
  maintainer: Ignacio Dominguez
  description: This is the 5GTANGO network service for the media pilot with monitoring
    integrated
files:
- path: Definitions/cms-vnfd.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: Definitions/ma-vnfd.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: Definitions/mse-vnfd.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: Definitions/mediapilot-ns.yml
  type: application/vnd.5gtango.nsd
  tags:
  - eu.5gtango
